### ISSUE TITLE
Simple help...

### ISSUE THREAD

**Issue by damien67** [milaq/kodi-headless#1]
Hi...
I have little experience with Docker, and am trying my best to get it.

Setup:
Debian 9.5
MariaDB 10.x installed on same server, not the docker version.

The kodi-server installed without issue, and I can start/stop it, access the web interface. I have however no idea where I can find the configuration files.

The script mentions a few locations, such as opt/kodi-headless/.kodi, but this directory doesn't exist. I can find the userdata directory in var/lib/docker/volumes/xxx/_data, but I don't think that is where I need to be.
It also mentions /sbin/kodi_init.sh, but not such file exists.

I manually created the opt/kodi-headless/.kodi directories, and pasted my config files in there, but the container logs clearly show  Unable to open database: MyMusic60. Things is...my databases aren't called "MyMusic" and "MyVideos", so I know the advancedsettings.xml entries aren't taken into account.

Am I completely off here??

I am a long time xbmc/Kodi user, and had a Windows MySQL/MariaDB database running for years.
I properly migrated my database over to Debian, and now I just need the kodi part of it for simple update purposes.

Thanks!!!

**Comment by damien67** [comment]
Ok...I guess I just had to learn some more about docker and answered all my questions myself.
The big question now is...

All my shares are on a Windows machine (which runs a couple Debian VMs, including the one running this). My source.xml has the following entry: smb://WINDOWSHOST/Media/Movies/, but the log show:

{"log":"14:48:02.558 T:140349878347520   ERROR: GetDirectory - Error getting smb://WINDOWSHOST/Media/Movies/\n","stream":"stdout","time":"2018-09-21T14:48:02.558991309Z"}

Any tip on the docker container accessing this windows share? Debian can get to it just fine...

**Comment by milaq** [comment]
There may be a couple of reasons why Kodi can't access your SMB shares.

I would go ahead and try if I can reach the Samba shares by hand via smbclient.
It may also help to turn on verbose logging and/or have a look at the network traffic between your VM and the SMB host.

**Comment by damien67** [comment]
Thanks for your reply...
smbclient can connect the share Win10 share, and fstab is able to mount them at boot.
The docker container is able to connect my NAS, but not Win10 shares. Kodi logs show "permission denied".

**Comment by milaq** [comment]
It _may_ be during to later versions of Windows disabling SMBv1 access by default.

I commited a fix that allows Kodi to try higher protocol versions first, before falling back to v1.
See https://github.com/milaq/kodi-headless/commit/2515df06ce01d7549ab5bde6a1ba14dace0c67ff

Try the latest Docker image from today (it should be built soon).
Please let me know if that fixes your problem.
