### ISSUE TITLE
User specified advancedsettings.xml gets overwritten

### ISSUE THREAD

**Issue by fritz-k** [milaq/kodi-headless#14]
Hi,

I need to add some custom settings to advancedsettings.xml. I can mount a custom one to /config/userdata/advancedsettings.xml but it gets overwritten unconditionally by kodi_init. Did I miss something? If not, I added a simple fix in #13.

Cheers,
Simon

**Comment by milaq** [comment]
Hey, thanks for your PR.

Maybe we can add in support for the docker initscript to detect whether an advancedsettings.xml was mounted inside the container, which would be much simpler.
That way, the user doesn't need to specify any additional environment variables.

**Comment by fritz-k** [comment]
Good idea, I'm not quite sure how easy that is though.

As a third option, I could mount the settings as read-only, if we changed the init script to not fail if it can't copy over it and change its ownership (possibly with a log message that you have to manually change it to UID:GID). Then adding a small paragraph in the README should be enough for other users.

**Comment by milaq** [comment]
Solved by https://github.com/milaq/kodi-headless/commit/3e9e6c13a7ef299ac663fa9dd960720274f958da.

Also see https://github.com/milaq/kodi-headless/pull/13
