### ISSUE TITLE
Make port optionally configurable

### ISSUE THREAD

**Issue by Shasoosh** [milaq/kodi-headless#18]
I see `KODI_DBHOST` but no way to configure the port.
My port is 3307 and not the standard 3306

**Comment by Staubgeborener** [comment]
Go into your `/usersdata/advancedsettings.xml` :
```shell
<videodatabase>
<type>mysql</type> <!-- don't change this value -->
<host>host</host> <!-- change this to the IP address of your mysql/ma>
<port>3307</port> <!-- change this to the port of your mysql/mariadb server  -->
<user>user</user> <!-- change this to the user for your database, not root  -->
<pass>pass</pass> <!-- change this to the password for your database -->
</videodatabase>
...
```
My database runs also on a separate `mysql` db (docker container) on `port 3307`.

**Comment by milaq** [comment]
Fixed by https://github.com/milaq/kodi-headless/commit/64169bb1fd667b99cd047b84848d4ade23503449

You may now use the environment variable `KODI_DBPORT` for that.
I triggered a new Docker hub build. The images should be up in the next few hours.
