### ISSUE TITLE
Avoid offscreen rendering

### ISSUE THREAD

**Issue by sinopsysHK** [milaq/kodi-headless#2]
I see Kodi is launched with xpra, thus having a offscreen display for rendering ?

Or is the rendering avoided ?

I’ve tried linuxserver.io version that looks similar and the container is consuming lot of cpu.

**Comment by milaq** [comment]
You are correct, we are using offscreen rendering at the moment.

If I find some time, I'll backport the headless patch from the [Krypton branch](https://github.com/milaq/kodi-headless/tree/krypton).
If you really need zero rendering and don't implicitly need Kodi leia, you can use the above Krypton branch for now.

If you do, please let me now if your CPU usage went down considerably.

**Comment by sinopsysHK** [comment]
Hello,

I was using previously the Krypton docker-kodi-headless and it was very lean in terms of CPU usage.
I had to move to Leia, reason why I was looking for new real headless version (tested X11 and GBM docker versions but both hit severely CPU).

As I couldn't find any, I've made my own patch : [https://github.com/sinopsysHK/xbmc/tree/headless](url)
It is working on my ubuntu VM and planning to containerize it if not integrated in master kodi codebase.
Still performing some tests before submitting a PR.

**Comment by milaq** [comment]
Yeah, I too didn't prefer the xpra approach but I needed a quick fix as all my other Kodi machines at home were already running Leia.

Nice, your patch looks good.
If I find the time, I'll try it out and integrate it into the leia branch here.

**Comment by milaq** [comment]
fixed by https://github.com/milaq/kodi-headless/commit/d9623d9799c4937c1ee3662128d6058ca62f2b9f

**Comment by milaq** [comment]
Thanks again for the headless patch.

Stellar work :+1:
