### ISSUE TITLE
Leia Addon Updates

### ISSUE THREAD

**Issue by netleader** [milaq/kodi-headless#20]
I just did a fresh install and the sources have old addons which is causing problems.
I'm a German user and my scrapers are using de-DE as a language code this was introduced with a tmdb/kodi update.
I had to manually copy the addons from my HTPC to the docker container which is not a good solution.

You can check the version of "metadata.themoviedb.org" the latest one is: 5.1.7

Your kodi-headless container is also not updating the addons automatically that would also solve the problem.

Cheers!

**Comment by milaq** [comment]
Hey there,
sorry for the late reply.

This should be fixed with https://github.com/milaq/kodi-headless/commit/8f00707e801c34a72cae17f05c27951ca9d64500
Addon updates happen on container start and every 6 hours by default from now on.

Cheers back!
