### ISSUE TITLE
Krypton config directory

### ISSUE THREAD

**Issue by bdwilson** [milaq/kodi-headless#21]
Your links to map sources.xml and passwords.xml should go to /config/.kodi/userdata/passwords.xml and /config/.kodi/userdata/sources.xml (you're missing .kodi directory in your docs).  I wasn't sure if this was true for newer versions too, but since it doesn't work on Krypton, I thought I'd report it.

**Comment by milaq** [comment]
For Leia I changed Kodi's config directory to `/config` directly so the paths are correct.
Thanks for the headsup nevertheless :)
