### ISSUE TITLE
DB name prefix not working

### ISSUE THREAD

**Issue by bdwilson** [milaq/kodi-headless#22]
advancedsettings.xml.default in your github repo doesn't seem to match that which is in docker hub. Tried many different ways to get db prefix working and it didn't work using docker hub version.

**Comment by milaq** [comment]
Weird.
What environment variables did you use?
`KODI_DBPREFIX_VIDEOS` and `KODI_DBPREFIX_MUSIC`?

Are we talking about the `leia` branch?

**Comment by bdwilson** [comment]
No, this was for Krypton.  This is what ended up working, creating advancedsettings.xml.default and calling it in my run script. In the above file, I have 
<pre>
&ltname>xbmc_video&lt/name> and &ltname>xbmc_music&lt/name>
</pre>

docker run -d --restart=always --name kodi-headless -p 8080:8080 -p 9090:9090 **-v /var/docker/kodi-krypton-headless/advancedsettings.xml.default:/config/.kodi/userdata/advancedsettings.xml.default** -v /var/docker/kodi-krypton-headless/sources.xml:/config/.kodi/userdata/sources.xml -v /var/docker/kodi-krypton-headless/passwords.xml:/config/.kodi/userdata/passwords.xml -e KODI_DBHOST=192.168.1.2 -e KODI_DBUSER=xbmc -e KODI_DBPASS=xxxx -e KODI_DBPREFIX_VIDEOS=xbmc_video -e KODI_DBPREFIX_MUSIC=xbmc_music -e KODI_CLEAN=yes -e KODI_UPDATE_INTERVAL=28800 milaq/kodi-headless:krypton

**Comment by milaq** [comment]
Ah, alright. In this case, it is a `wontfix`.
This feature is only available in Leia and was not backported to Krypton.

You may check the supported parameters here:
https://github.com/milaq/kodi-headless/blob/krypton/README.md

Glad you got it working though.
