### ISSUE TITLE
Media path

### ISSUE THREAD

**Issue by akshatgit** [milaq/kodi-headless#3]
Thanks for sharing this wonderful docker image. I am new to kodi, and I wanted to know how to add a media path.
My setup:
Download folder: /home/deluge

I want to add this download folder to my video path

**Comment by milaq** [comment]
You need to use a GUI client, i.e. your "media center", which is also using the same remote database to add video paths.

From the readme:

> Best way to set up library sharing in the container is by fully configuring your shared library, its sources and scrapers via another GUI host (e.g. your HTPC) and setting up the Kodi headless instance afterwards. The server needs fully configured database access and your sources (SMB or NFS) must be reachable from the headless instance. All updating, scraping and cleaning can then be handled automatically by the headless Kodi instance on its own.
