### ISSUE TITLE
Specific Kodi Version

### ISSUE THREAD

**Issue by raupie** [milaq/kodi-headless#5]
How would I explicitly state to use 18.2 and not 18.3? Been burned on being an early adopter of a new version once or twice.

**Comment by raupie** [comment]
I'm an idiot. 

`DockerFile` -> ARG KODI_VERSION="<VERSION>"

**Comment by raupie** [comment]
I guess that doesn't help. The current image on docker hub would pull 18.3. I don't see any 18.2 tags.

**Comment by milaq** [comment]
You can set a specific `KODI_VERSION` in the Dockerfile, that's correct.
You would of course need to build the image by yourself after modifying the Dockerfile. Everything you pull from Docker Hub has the latest repository state as tagged.

As 18.2 > 18.3 are minor version jumps, I'll not consider any additional tags. If you want maximum compatibility, you can always use the older `krypton` branch.

**Comment by raupie** [comment]
Why not tag minor versions? Being able to use a shared mysql database has the requirement that all kodi devices are on the same version. It's a major roadblock in my opinion and forces whoever to use this docker image to always update their kodi devices to the current release. 

I really didn't want to have to clone my own branch of this to manage one line.

**Comment by milaq** [comment]
You are misinformed.
A shared database setup does _not_ require you to be on the same minor version but only major version.

Using 18.2 and 18.3 clients together on the same db is fine.

**Comment by raupie** [comment]
Oh sweet. I had always assumed the same build was important via this documentation: `https://kodi.wiki/view/MySQL`. 

I wasn't able to find any kodi documentation about minor vs major versions for the shared database. I'm going to try this out now with 18.3 as the headless-kodi.
