### ISSUE TITLE
Rancher

### ISSUE THREAD

**Issue by raupie** [milaq/kodi-headless#6]
Any experience of getting this to work with Rancher on FreeNAS?

**Comment by milaq** [comment]
Unfortunately, not by myself.
But I'll keep this open for reference and to be possibly answered by other users.

**Comment by raupie** [comment]
I'm currently attempting to get this to work on RancherOS on FreeNAS and the hold up is my Kodi versions.

**Comment by raupie** [comment]
I was able to get this working on FreeNAS + RancherOS. 

It was pretty straight forward. Have to create the container and add all the ENV you want. 

The one thing I didn't catch right away is where to store the `sources.xml` file on the rancherOS VM. Since Rancher itself is based on docker, you have to be careful where you store your files so they are persistent. I ended up putting my `sources.xml` file inside the `/home/docker/kodi/sources.xml` location. 

It's important that your NFS shares on FreeNAS are set with the `Allow non-root mount`. The one issue I ran into is my TV Shows not being updated but my Movie collection is.
